### ISSUE TITLE
Use InjectionToken<?> instead of OpaqueToken

### ISSUE THREAD

**Issue by RicardoJBarrios** [phillipcurl/ngx-warehouse#2]
OpaqueToken have been [removed from Angular 5](https://blog.angular.io/version-5-0-0-of-angular-now-available-37e414935ced). They propose [InjectionToken](https://angular.io/api/core/InjectionToken) as the alternative.

This makes ngx-warehouse not usable with Angular 5.

**Comment by phillipcurl** [comment]
@RicardoJBarrios I'm taking a look at this now. I haven't used Angular in a few months, but it looks like this should be an easy fix. I'm also updating all dependencies since this was still relying on Angular 2.x. I'll let you know when I've pushed a new version. Thanks for bringing it to my attention!

**Comment by phillipcurl** [comment]
@RicardoJBarrios This has been resolved and I released v1.0 to npm. Take a look when you get a chance and let me know if you're still experiencing the issue.

**Comment by RicardoJBarrios** [comment]
Thanks @phillipcurl. I have tested it and works. Great job.
